server:
  port: 45031
  servlet:
    context-path: /ProjectGenerator

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_generator?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ENC(Ih3JxNYTxDRX0q8GuVPC4A==)
    password: ENC(oRxH0gJgsz8g5+LymmJ2fC04CIjUlIKu)
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1